export enum tournamentConstants {
    TOURNAMENT_NEW_REQUEST = 'TOURNAMENT_NEW_REQUEST',
    TOURNAMENT_NEW_SUCCESS = 'TOURNAMENT_NEW_SUCCESS',
    TOURNAMENT_NEW_FAILURE = 'TOURNAMENT_NEW_FAILURE',

    TOURNAMENT_GETALL_REQUEST = 'TOURNAMENT_GETALL_REQUEST',
    TOURNAMENT_GETALL_SUCCESS = 'TOURNAMENT_GETALL_SUCCESS',
    TOURNAMENT_GETALL_FAILURE = 'TOURNAMENT_GETALL_FAILURE',
}
